def hide(input_img: str, output_img: str, file_path: str,
         password: str | None = None,
         expires_days: int | None = None,
         expires_hours: int | None = None,
         expires_minutes: int | None = None,
         expires_seconds: int | None = None,
         mode: str = "chunk") -> str: ...

def read(input_img: str, output_path: str,
         password: str | None = None) -> dict: ...

def info(input_img: str,
         password: str | None = None) -> dict: ...

def verify(input_img: str, password: str) -> bool: ...

def delete(input_img: str, output_img: str,
           password: str | None = None) -> str: ...

def reencrypt(input_img: str, old_password: str,
              new_password: str, output_img: str) -> str: ...

def capacity(input_img: str, mode: str = "chunk") -> int: ...

def fingerprint(input_img: str) -> str: ...

def batch_hide(input_imgs: list[str], output_dir: str,
               file_path: str, password: str | None = None,
               **expiry) -> list[dict]: ...

def batch_read(input_imgs: list[str], output_dir: str,
               password: str | None = None) -> list[dict]: ...

def split(file_path: str, carrier_imgs: list[str],
          output_dir: str, password: str | None = None,
          **expiry) -> list[str]: ...

def merge(input_imgs: list[str], output_path: str,
          password: str | None = None) -> str: ...